### PR TITLE
Add LABELs to conversion page

### PR DESCRIPTION
**Pull request by dan2468**
This allows clicking on the option name to toggle the options checkboxes.

### CODE REVIEW

**Comment by kalenobr** [comment]
And labels

**Comment by r12a** [comment]
Thanks for the suggestion. It's certainly something i should have done, but I'm planning to move the app to https://r12a.github.io/app-conversion/ soon.  So I have added label tags there.  Please try using that version instead and  I'll close this PR.

**Comment by dan2468** [comment]
Sounds good.

Presumably http://rishida.net/tools/conversion/ will redirect there, too.

**Comment by r12a** [comment]
Yes it will. I just want to find the time to make a couple more changes to the new version before setting the redirects.

**Pull request closed without merging**
