### PR TITLE
Updating a relocated Urdu reference, fixes #11

### LINKED ISSUE #11: An Urdu reference needs update due to the content reocation
Dr. Kamal Abdali's site hosted on http://patriot.net/~abdali/ has been relocated to http://geomete.com/ after several years. Corresponding references on Urdu pages need to be updated.

### PR DESCRIPTION
**Pull request by ibnesayeed**
Fixes #11

### CODE REVIEW

**Comment by r12a** [comment]
Edits made manually. /scripts/urdu removed in favour of /scripts/arabic/urdu

**Comment by ibnesayeed** [comment]
Since, you have removed a duplicate page which might be linked from or bookmarked in many places. Should you consider to [set up a redirect](https://help.github.com/articles/redirects-on-github-pages/) to the canonical page?

**Comment by r12a** [comment]
Yes, thanks. I put a manual redirect in place for now.

**Comment by ibnesayeed** [comment]
I understand that you are not using Jekyll, so can't really use the server side redirect. However, you may consider adding [JavaScript and/or HTML based automatic redirects](https://css-tricks.com/redirect-web-page/) (after 5 seconds or so) on the page with the existing not in place.

**Pull request closed without merging**
